name: GITHUB_OUTPUT
on: push
jobs:
  share:
    runs-on: ubuntu-latest
    steps:
      - id: test
        run: echo "animal=Cat" >> "${GITHUB_OUTPUT}"
      - env:
          PET: ${{ steps.test.outputs.test }}
        run: echo "${PET}"
