name: Secrets
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      TESTPASS: ${{ secrets.TESTPASS }} # 中間環境変数を経由させる
      PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - run: echo "${TESTPASS}" # 環境変数の出力では必ず "" で囲む
      - run: echo "${TESTPASS:0:1} ${TESTPASS#?}"
      - run: echo "${PASSWORD}"
      - run: echo "${PASSWORD:0:1} ${PASSWORD#?}"
